sudo: false
language: php
php:
  - 7.0

before_install:
  - mkdir -p /tmp/wordpress
  - cd /tmp/wordpress
  - git clone https://github.com/paulgibbs/paul-hates-travis-ci-debugging.git .
  - phpenv config-rm xdebug.ini
  - node --version
  - nvm install 4
  - node --version
  - npm install -g grunt-cli
  - npm --version
  - mysql --version
  - phpenv versions

before_script:
  - npm install

# Run tests
script:
  - grunt
  - phpdbg -qrr "phpunit" -c codecoverage.xml --coverage-clover clover.xml
