sudo: true
language: php

php:
  - 7.1

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - WP_VERSION=latest BEHAT_PARAMS='{"extensions":{"PaulGibbs\\WordpressBehatExtension":{"default_driver":"wpapi"}}}' WH_BUILD_DOCS=1

before_install:
  # Set up Behat.
  - export WH_DIR=$(pwd)
  - export WH_NGINX_DIR=/tmp
  - export WH_WORDPRESS_DIR="$WH_DIR/www/"

install:
  # Install all of the dependencies you need here.
  - echo $TRAVIS_PHP_VERSION;
  - if [[ "$TRAVIS_PULL_REQUEST" = "false" && "$WH_BUILD_DOCS" = "1" && "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PHP_VERSION" = "7.1" ]] ; then sudo -H pip install --upgrade pip && sudo -H pip install --upgrade pymdown-extensions pygments mkdocs mkdocs-material; fi
  - which mkdocs
  - ls -la ~/.local/bin/
