# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

#cache:
#  apt: true
#  directories:
#    - /tmp/wordpress/src/wp-content/plugins/buddypress/node_modules

php:
  - 7.0

# WordPress comes from the Git mirror, where 'master' mirrors svn 'trunk' and
# x.y mirrors the latest from the x.y branch
env:
  - WP_VERSION=master BP_TRAVISCI=travis:phpunit

matrix:
  fast_finish: true
  include:
    - env: WP_VERSION=master BP_TRAVISCI=travis:codecoverage
      php: 7.0
  allow_failures:
    - env: WP_VERSION=master BP_TRAVISCI=travis:codecoverage

# before_install: Failures in this section will result in build status 'errored'
before_install:
  - python --version
  - pip --version

notifications:
  email: false
