sudo: false
language: php

php:
  - 7.1

cache:
  apt: true
  pip: true
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - WP_VERSION=latest BEHAT_PARAMS='{"extensions":{"PaulGibbs\\WordpressBehatExtension":{"default_driver":"wpapi"}}}'
    - WP_VERSION=latest BEHAT_PARAMS='{"extensions":{"PaulGibbs\\WordpressBehatExtension":{"default_driver":"wpcli","wpcli":{"binary":"%paths.base%/../../vendor/bin/wp"}}}}'
    - WP_VERSION=nightly BEHAT_PARAMS='{"extensions":{"PaulGibbs\\WordpressBehatExtension":{"default_driver":"wpapi"}}}'
    - WP_VERSION=nightly BEHAT_PARAMS='{"extensions":{"PaulGibbs\\WordpressBehatExtension":{"default_driver":"wpcli","wpcli":{"binary":"%paths.base%/../../vendor/bin/wp"}}}}'

matrix:
  allow_failures:
    - env: WP_VERSION=nightly BEHAT_PARAMS='{"extensions":{"PaulGibbs\\WordpressBehatExtension":{"default_driver":"wpapi"}}}'
    - env: WP_VERSION=nightly BEHAT_PARAMS='{"extensions":{"PaulGibbs\\WordpressBehatExtension":{"default_driver":"wpcli","wpcli":{"binary":"%paths.base%/../../vendor/bin/wp"}}}}'

addons:
  apt:
    packages:
      - nginx
  hosts:
    - wordpress.dev

before_install:
  # Execute all of the commands which need to be executed before installing dependencies.
  - composer self-update
  - composer validate
  - phpenv config-rm xdebug.ini
  - export WH_DIR=$(pwd)
  - export WH_NGINX_DIR=/tmp
  - export WH_WORDPRESS_DIR="$WH_DIR/www/"

install:
  # Install all of the dependencies you need here.
  - composer install --no-interaction --prefer-dist --no-progress
  - pip install --user pymdown-extensions pygments mkdocs mkdocs-material
  - bin/travis/wordpress.sh wordpress root '' localhost $WP_VERSION
  - bin/travis/nginx.sh

before_script:
  # Execute all of the commands which need to be executed before running actual tests.
  - bin/travis/selenium.sh

script:
  # Execute all of the commands which should make the build pass or fail.
  - find ./src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - vendor/bin/phpcs --standard=phpcs-ruleset.xml -p -s -v -n src --extensions=php
  - vendor/bin/behat --config ./bin/travis/behat.yml

after_success:
  # Update document website after succesful tests.
  - if [[ "$WP_VERSION" = "latest" && "$TRAVIS_PHP_VERSION" = "7.1" ]] ; then mkdocs gh-deploy; fi

after_script:
  # Tidy up after test run.
  # See https://github.com/travis-ci/travis-ci/issues/6861
  - kill -9 $(ps aux | grep 'selenium' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'java' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'Xvfb' | awk '{print $2}')
