sudo: false
language: php
php:
  - 7.0

before_install:
  - phpenv config-rm xdebug.ini
  - node --version
  - nvm install 4
  - node --version
  - npm install -g grunt-cli
  - npm --version
  - mysql --version
  - phpenv versions
  - mkdir /tmp/wordpress
  - cd /tmp/wordpress

before_script:
  - npm install

# Run tests
script: grunt
